[target.thumbv6m-none-eabi]
runner = 'probe-rs run --chip STM32F070F6Px'

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"

# [unstable]
# build-std = ["core"]
# build-std-features = ["panic_immediate_abort"]
